### ISSUE TITLE
weak encryption algorithm Luks type  1

### ISSUE THREAD

**Issue by onlineapps-cloud** [AdrianTM/mx-live-usb-maker#6]
hi, i tried right now this tool and i saw in logs that is used Luks type  1, can you change encryption algorithm for more secure Luks type  2?

**Comment by AdrianTM** [comment]
There's nothing related to Luks in this repo.

**Comment by onlineapps-cloud** [comment]
i talk about this option, that encrypt usb flash using LUKS 1
![image](https://github.com/user-attachments/assets/603728e9-e1b3-4bc6-8db1-c81decca0426)

**Comment by AdrianTM** [comment]
That option is from the underlying CLI tool. this MX Live USB maker is just the GUI around that tool. It simply adds a "-E" option. You might want to report that here: https://github.com/BitJam/live-usb-maker

**Comment by onlineapps-cloud** [comment]
hi again, developer give answer about luks 2
```
There is a command line option --force=luks2 that changes the encryption
type to luks2.  This was not advertised because (I think) luks2 didn't work
from within busybox which performs the early boot process. Or something
like that.  If this problem has been fixed and if a new fixed version of
busybox is used then --force=luks2 should make a working encrypted live-usb
using luks2.
```
but i don't know if this will work with mxlinux distribution, or other distribution, can you say, it will work?

**Comment by AdrianTM** [comment]
Thanks for the reply, don't know either, haven't tested. One quick test would be to use CLI tool: live-usb-maker with --force=luks2 and let us know if that worked well for you.

**Comment by onlineapps-cloud** [comment]
report about LUKS2 support: **it's working!**
i able to made bootable usb drive and boot from USB without problems, like as luks1, can you add additional checkbox to use luks2 encryption?
![image](https://github.com/user-attachments/assets/9b6f37bf-906e-46f0-80ba-11d673b65035)
`luks 2 encryption:`
![image](https://github.com/user-attachments/assets/3e9dee09-7a9f-4992-83a8-41bf5b8175c1)
![image](https://github.com/user-attachments/assets/823004f3-0ec0-42f8-a6e6-e8a91edf2a10)

**Comment by AdrianTM** [comment]
Sure, thanks for confirming, just need to think about the UI a bit, maybe do a dropbox with LUKS1 | LUKS2...

**Comment by onlineapps-cloud** [comment]
yes, drop down, will be great!

**Comment by AdrianTM** [comment]
Resolution: we'll modify live-usb-maker script to use luks2 by default.
