### ISSUE TITLE
[Idea] A new persistent mode

### ISSUE THREAD

**Issue by ghost** [AdrianTM/mx-live-usb-maker#7]
I only want the home directory to be persisted, and for performance it should be on RAM and only synced to the persistent file on reboot/shutdown. Currently, there is no such a persistent mode. `persist_home` will write directly to the persistent file and thus the performance is terrible. I have no idea why such a use case is not discovered given the long history of MX Linux. Or am I missing something?

**Comment by AdrianTM** [comment]
This is not really related to mx-live-usb-maker tool, please post feature requests on forum.
You are right, you cannot have /home in RAM by itself
